/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import service.Trancelate;

/**
 *
 * @author Dejan
 */
public class TrancelateForm extends javax.swing.JFrame {

    /**
     * Creates new form TrancelateForm
     */
    public TrancelateForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        resultTextField.setEnabled(false); 
        targetLangComboBox.setEnabled(false);
        trancelateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        sourceLangComboBox = new javax.swing.JComboBox<>();
        targetLangComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trancelateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dejan Trancelate");
        setResizable(false);

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTextField.setToolTipText("Enter required word here");
        searchTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        sourceLangComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sourceLangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose:", "Serbian", "English" }));
        sourceLangComboBox.setToolTipText("Choose one option");
        sourceLangComboBox.setMinimumSize(new java.awt.Dimension(150, 28));
        sourceLangComboBox.setPreferredSize(new java.awt.Dimension(150, 28));
        sourceLangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceLangComboBoxActionPerformed(evt);
            }
        });

        targetLangComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        targetLangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose:", "Serbian", "English" }));
        targetLangComboBox.setToolTipText("Choose one option");
        targetLangComboBox.setMinimumSize(new java.awt.Dimension(150, 28));
        targetLangComboBox.setPreferredSize(new java.awt.Dimension(150, 28));
        targetLangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetLangComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Source language:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Target language:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter the word you want to translate in the text field:");

        trancelateButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        trancelateButton.setText("Trancelate");
        trancelateButton.setToolTipText("Push the button to trancelate");
        trancelateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trancelateButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Result:");

        resultTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resultTextField.setForeground(new java.awt.Color(255, 0, 0));
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(sourceLangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(targetLangComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(trancelateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sourceLangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(targetLangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(trancelateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceLangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceLangComboBoxActionPerformed
        
        int sourceLang = sourceLangComboBox.getSelectedIndex();
        
        switch(sourceLang){
            
            case 0:
                
                resultTextField.setEnabled(false); 
                targetLangComboBox.setEnabled(false);
                trancelateButton.setEnabled(false);
                
            break;
            case 1:
                
                resultTextField.setEnabled(false); 
                targetLangComboBox.setEnabled(true);
                trancelateButton.setEnabled(false);
                
            break;
            case 2:
                
                resultTextField.setEnabled(false); 
                targetLangComboBox.setEnabled(true);
                trancelateButton.setEnabled(false);
                
            break;    
        }
    }//GEN-LAST:event_sourceLangComboBoxActionPerformed

    private void targetLangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetLangComboBoxActionPerformed
        
        int targetLang = targetLangComboBox.getSelectedIndex();
        
        switch(targetLang){
            
            case 0:
                
                resultTextField.setEnabled(false);
                trancelateButton.setEnabled(false);
                
            break;
            case 1:
                
                resultTextField.setEnabled(false);
                trancelateButton.setEnabled(true);
                
            break;
            case 2:
                
                resultTextField.setEnabled(false);
                trancelateButton.setEnabled(true);
                
            break;
        }
    }//GEN-LAST:event_targetLangComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        
        resultTextField.setEnabled(false); 
        targetLangComboBox.setEnabled(false);
        trancelateButton.setEnabled(false);
        searchTextField.setText("");
        resultTextField.setText("");
        sourceLangComboBox.setSelectedIndex(0);
        targetLangComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void trancelateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trancelateButtonActionPerformed
        
        resultTextField.setEnabled(true);
        
        try {
            
            URL url = new URL("http://desktop-u6kst70:8080/JavaWebService_service/TrancelateImplService?wsdl");
            QName qName = new QName("http://service/", "TrancelateImplService");
            Service service = Service.create(url, qName);
            QName port = new QName("http://service/", "TrancelateImplPort");
            
            Trancelate trancelate = service.getPort(port, Trancelate.class);
            
            resultTextField.setText(trancelate.trancelate(searchTextField.getText(), sourceLangComboBox.getSelectedItem().toString(), targetLangComboBox.getSelectedItem().toString()));
            
        } catch (MalformedURLException ex) {
            
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_trancelateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrancelateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrancelateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrancelateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrancelateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrancelateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> sourceLangComboBox;
    private javax.swing.JComboBox<String> targetLangComboBox;
    private javax.swing.JButton trancelateButton;
    // End of variables declaration//GEN-END:variables
}
